version: '2'
services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - '27017:27017'
  web:
    image: node:latest
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - '3000:3000'
    links:
      - mongodb
